spring.application.name=bms-august
spring.datasource.url=jdbc:postgresql://localhost:5432/bms-august-2026
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update