package com.acciojobs.bms_august.securites;

import io.jsonwebtoken.Claims;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

@Component
public class JwtFilter extends OncePerRequestFilter {

    private JwtUtility jwtUtility;

    @Autowired
    public JwtFilter(JwtUtility jwtUtility){
        this.jwtUtility = jwtUtility;
    }

    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain) throws ServletException, IOException {
        String bmsToken = request.getHeader("bmsToken");
        if (bmsToken == null || bmsToken.trim().isEmpty()) {
            // If we are calling doFilter without setting some kind of authentication that means we are rejeting request.
            filterChain.doFilter(request, response);
            return;
        }
        // We need to verify the token
        // If we are able to extract the claims out of the token that means this token is not tempered and is generated by us.
        Claims claims = jwtUtility.extractAllClaims(bmsToken);

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(claims, null, null);
        SecurityContextHolder.getContext().setAuthentication(authentication);

        filterChain.doFilter(request, response);
    }
}
